### ISSUE TITLE
Make styling of the day cell content possible.

### ISSUE THREAD

**Issue by kornicameister** [CurrySoftware/elm-datepicker#1]
Use case:

I wanted to style the selected day and those user can select (i.e. `:hover`) as round. It was quite easy to achieve, but there's a certain flickery effect when hovering near the border between two cells. I bet that the reason for it was this piece of code:

```
.#{$datepicker-ns}day {
     cursor: pointer;
     color: $black;
    
     &:hover {
       background: $datepicker-hl;
       border-radius: 100%;
       color: $datepicker-picked-fg;
     }
}
```

I wonder if we couldn't maybe put a `<button/>` inside or at least a `<span/>`, although maybe more appropriate is `button/>` just because of HTML semantics as something user can click. Anyway, doing that would enable to style the content of the call directly and easier.

**Comment by kornicameister** [comment]
ping @JDemler

**Comment by JDemler** [comment]
Could you please put your example on ellie and send me a link? 
It would be much easier to understand your problem.

[Here](https://ellie-app.com/3c5q4kSYVmxa1) is the simple example which may be a good starting point.

**Comment by kornicameister** [comment]
I will try to come up with replicated example from my own codebase.

Nevertheless, even if I got something wrong, I am quite certain that something clickable should be represented with something a little bit more adequate. But let's start with some better example here.

**Comment by kornicameister** [comment]
@JDemler here's the example from my own codebase as far as identical when it comes to styling (also includes bulma, since that's the thing I am using).

[example](https://ellie-app.com/3dtJqBNkqFFa1)

So the flickering part occurs if you place your course between two cells in the upper part of the cell border (that's of course invisible in the example, but it still there).

**Comment by JDemler** [comment]
Now I understand what you need!

Have a look at the `Settings.cellFormatter`.

It's `String -> Html Msg`. You can put any html in the cell.

The default is:

``` elm
formatCell : String -> Html Msg
formatCell day =
    text day
```

Just add whatever buttons or spans you need.
[Example](https://ellie-app.com/3dtSnQk4kQha1) that adds a span for every cell. Does not yet solve your flickering problem but I think you're good to go from here.

**Comment by kornicameister** [comment]
Ahh...so obvious. I noticed other formatters, but missed that one. Yeah, so I think that we can close this issue down since it is actually possible to overwrite default content of the cell.
