### ISSUE TITLE
Possible issue with Browser.application?

### ISSUE THREAD

**Issue by michaeljones** [CurrySoftware/elm-datepicker#12]
Hi, thanks for maintaining this project! It was a relief to see it being ported to Elm 0.19.

I've been updating our app to Elm 0.19 and we're using `Browser.application` and that seems to listen to all the `a` tags in the DOM and act on the click events. Unfortunately I think this might mean that we're getting weird interactions with the left & right arrows in the DatePicker as they use `a` tags.

Have you seen this at all? I'm currently tracking down different bugs in my app due to this `a` tag behaviour  and I'm not at all sure that I understand it correctly. In this case however, as no page navigation is taking place it seems like it might be reasonable to model them with `button` tags instead?

**Comment by JDemler** [comment]
Thanks for reporting this issue.

I see two possible solutions:
Turning the `a`-tag into a `button` or a `div` tag.

With `div`:
![image](https://user-images.githubusercontent.com/12686782/46074082-e49be300-c186-11e8-8a4a-322def5559b2.png)

With `button`:
![image](https://user-images.githubusercontent.com/12686782/46074126-ff6e5780-c186-11e8-8c5a-a97f8c6f0dad.png)

They both work and pass the tests. Button looks different though and would result in a change of css.
As that would require all users to update their css I am a bit reluctant to do this.

Are there any arguments against using `div` instead of `button`?

**Comment by michaeljones** [comment]
I'm afraid I'm tempted to suggest that the `button` is more semantically correct, and I think it is more accessible, so that is what a library should provide. The CSS change is less than ideal but the visual inconsistency is minor.  

I understand your concern though and respect the decision you make.

**Comment by JDemler** [comment]
That makes sense.

This will result in a breaking change, but as we already have a breaking change queued, I think it is acceptable. I will release the change made in #10 and this one together.

**Comment by michaeljones** [comment]
Great, thanks! Yeah, I saw that change. I really like what you've done with providing the extra `init*` functions that don't produce commands and this looks like another good change!

**Comment by JDemler** [comment]
Commit 87ca453 fixes this issue and turns the `a`-tags into `button`-tags with a seemingly trivial css chage.

Would it be possible for you to test it in your `Browser.application` use-case?
After that I would release this change together with #10.

**Comment by michaeljones** [comment]
Hi, I've already copied the code into my project and made the `a` to `button` change. It does seem to solve the problem. Hadn't taken the time to address the css to happy to see that :) I'll revert back installing your module once this is released!

**Comment by JDemler** [comment]
Release in https://package.elm-lang.org/packages/CurrySoftware/elm-datepicker/3.0.0/

**Comment by JDemler** [comment]
For future reference: 
Another alternative, that would not have resulted in a breaking style change, is to use the `role` attribute on the div:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role

**Comment by michaeljones** [comment]
Thanks for sharing the knowledge. Definitely something I should learn more about.
