### ISSUE TITLE
When clicking to change month it submits the form

### ISSUE THREAD

**Issue by gabriela-sartori** [CurrySoftware/elm-datepicker#14]
Even on the Ellie given example, when clicking to change to another month, it submit the form instead of showing other month. I am using google chrome.

**Comment by JDemler** [comment]
Can be fixed by adding `type = "button"` to the button as described [here](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element)

Will try to push a fix as soon as possible.

**Comment by gabriela-sartori** [comment]
Great! So I am closing.

**Comment by JDemler** [comment]
It's not yet fixed. I'll close it as soon as it lands on https://package.elm-lang.org/.
Thanks for reporting the bug, anyways.

**Comment by JDemler** [comment]
Fixed an published under [3.0.1](https://package.elm-lang.org/packages/CurrySoftware/elm-datepicker/3.0.1/)

Please be aware that when using the datepicker inside a form, you will run into trouble when trying to manually enter dates in the input field and pressing enter. This submits the form.
You need to handle that yourself as I do not see an easy way to fix this problem on the `elm-datepicker` side.

Have a look at the `nightwatch-simple` example for a possible solution (which disabled form submitting completely).
