### ISSUE TITLE
Examples from commit 35254e8 seem inconsistent

### ISSUE THREAD

**Issue by inspiredlabs** [CurrySoftware/elm-datepicker#16]
Weekends are grey and non-selectable (Version 72.0.3612.0 (Official Build) canary (64-bit) and Firefox Quantum 63.0.1 (64-bit)): https://ellie-app.com/3t52wzTZxdda1

The page doesn't display on Chrome when you use the arrows to pick December (Version 72.0.3612.0 (Official Build) canary (64-bit)):
https://ellie-app.com/3t52wzTZxdda1

**Comment by JDemler** [comment]
Weekends are meant to be grey and non-selectable:

```
settings : DatePicker.Settings
settings =
    let
        isDisabled date =
            [ Sat, Sun ]
                |> List.member (weekday date)
```


The other problem is a bug fixed in 3.0.1 (see #14). I updated the examples!
