### ISSUE TITLE
Is there plan to send dates entered directly into text-input?

### ISSUE THREAD

**Issue by jirisliva** [CurrySoftware/elm-datepicker#19]
Is there plan to send dates entered directly into text-input?
DatePicker send internal msg SubmitText with current text-input value but client code cannot access it.

**Comment by jirisliva** [comment]
I found out my miss-understanding. Value from text-input is parsed but default parser cannot parse strings from default formatter. 
This is quite confusing.

**Comment by JDemler** [comment]
sorry for the late reply...

Yes, I understand this is confusing and not optimal. 
Will look into it!

**Comment by JDemler** [comment]
So, the obvious solution is changing either the default formatter or the default parser...
Both changes break things and this issue is too small to justify a breaking change.
