### ISSUE TITLE
Impossible to directly intercept invalid string error.

### ISSUE THREAD

**Issue by kornicameister** [CurrySoftware/elm-datepicker#2]
How to reproduce:

- type in something that's not a date or not pass the `parser` (date in a wrong format from the one that parses understands).

Why impossible:

- `Result.withDefault NoChange`

Use case:

- I have a `range` like example in my codebase and I've applied some validation to it. However now, if user types in `baddate`, I don't have any easy way to fetch that error and display an error help text informing the user that his/her manual input is not correct.

**Comment by kornicameister** [comment]
@JDemler just to be clear, I could get the `DatePicer.Model.textInput` and apply the default parser of the one that I've applied to the settings over aforementioned value. It just seems a bit awkward. 

I see two possible approaches here:

- stop hiding the parser results and just pass them over directly as a 3rd element in a tuple returned from `update`
- expose some sort of function `DatePicker.validate`. That however is a bit tricky because we would have to pass error message that we wish to return for the user, I don't suppose forcing user to the message this library offer is a best choice.

Or maybe there are some ideas you'd have if you agreed with me here.

**Comment by JDemler** [comment]
Yeah that seems to be a problem.

Following suggestion: 
Parser is `Result String Date` so we get a `String` whenever parsing fails.

So `DateEvent` could be changed to include a failed parsing attempt:

`ParserError String`

Changing the `DateEvent` type though would be a breaking change...

**Comment by kornicameister** [comment]
Yes, I know it would but either of solutions will be such unless you have some idea how to go without that. Luckily packaging system will take care of that and indicate that change with appropriate new version.

BTW. I just noticed that `DateEvent` is somewhat misleading. For instance, I'd personally expect `NoChange` to be returned also for the case where newly selected date is the one that was just selected. I guess I am just after the `Name` that somehow suggests that possibility.

**Comment by JDemler** [comment]
There is another case, which would be useful to learn about:

When the user types a date, that is disabled.

Following suggestion:
`Changed Nothing` currently only happens in combination with typed dates.
For three reasons:

1. Empty string is submitted
2. Invalid string is submitted
3. Valid string which represents a disabled date is submitted

So let's add and remove complexity:
Merge 1. and 2. (both invalid strings); remove the `Maybe` from `Changed` and add a `FailedInput` event.
While were at it lets fix the naming inconvenience and rename `NoChange` to `None`:

```
type DateEvent
    = None
    | FailedInput InputError
    | Changed Date


type InputError
    = Invalid String
    | Disabled Date
```

Would that satisfy your usecase?

**Comment by kornicameister** [comment]
I guess I'd have to store both actual `Date` and the `InputError` inside my own model for the sake of validation, but that would at least allow to me to incorporate that information inside the `validate` function. 

BTW. Why would empty string be considered as invalid input. There's no input after thus nothing `parser` can parse and that can result in parsing error thus `Invalid`. I think empty input is efficiently handled by representing `Date` as `Maybe` in the caller model. If someone wishes the field to be required he may choose to fail the validation if it's not `Just`.

**Comment by JDemler** [comment]
Currently: 
1. If you press enter and the input is whitespace you get `Changed Nothing`, the input field resets.
2. If you enter nothing (empty string) the `changed` is not fired, nothing happens.
3. If you enter an invalid string you get `NoChange`.

Both 1. and 3. would with the proposed change result in `DateEvent.FailedInput`
I think thats reasonable.

Maybe `Changed` should be renamed to `Selected` as well...

**Comment by kornicameister** [comment]
Yeah, I think `Changed` -> `Selected` is not necessary. Both are OK, but `Change` somehow seems nicer because it covers not only what `Selected` covers but also manual valid input. 

But I'd still reconsider the case for `empty` string. From my POV `empty` input is invalid only if the field is required. Only checking `inputAttributes` to see if user has set `Attribute.required True` covers your idea. Then again, is it correct for library to decide that? However, I agree that a case where input is "cleared" should be covered. What about explicit "DateEvent.Reset" event to cover that?

**Comment by kornicameister** [comment]
@JDemler what do you think about recent idea. If you agree we can come with some plan and it will be a pleasure to submit a PR for this.

**Comment by JDemler** [comment]
As you said: `Changed` and `NoChange` are a bit misleading, because the same date as the current one could have been selected. If we break the API, lets do it right.

How about `Picked`, after all it's a `DatePicker`.

What I said in the comments above is partly wrong. On empty string, the browser does not fire the `change` event, so nothing happens. 
The current code checks if the input string is whitespace:
```elm
isWhitespace =
                            String.trim >> String.isEmpty
```

If it is just whitespace, it is treated differently than a invalid string. I think that is wrong.

I will implement the changes I proposed and notify you. Then you can check if it satisfies your usecase.

**Comment by JDemler** [comment]
Check out the `nightwash-simple` example in the new PR (#4).
Tell me if it satisfies your usecase, then I will add documentation and publish the change.

**Comment by JDemler** [comment]
Docs and package have been updated: https://package.elm-lang.org/packages/CurrySoftware/elm-datepicker/latest/

Thanks for raising this issue!
