### ISSUE TITLE
Year selector

### ISSUE THREAD

**Issue by SylvieC** [CurrySoftware/elm-datepicker#22]
Thank you for this package. In the predecessor elm-community/elm-datepicker, we could have a dropdown to change the year. Is this going to be implemented in this datepicker too?

**Comment by JDemler** [comment]
This functionality hasn't been touched during migration. It should behave as before.

Working example: https://ellie-app.com/4XSYRfmZHjTa1

**Comment by SylvieC** [comment]
@JDemler Thanks! My bad, the page I was using didn't have the year dropdown when I thought it had it before. Thank you for taking the time to write an example.  
I am having an issue when the date was saved and then the user tries to set it to Nothing. It doesn't accept it. 
 In the predecessor, when no date was chosen, it was automatically handled correctly as Nothing. 
I think it is because we were monitoring changes both from input field and from picking a date,  and not only if a date was clicked in the datepicker calendar. 
In the old version, we had 
```
                date =
                    case mDate of
                        DatePicker.Changed date ->
                            date

                        _ ->
                            model.date

                newOrg =
                    updateOrganization model.organization (ChgContractDate (formatMaybeDate date))``

Now,  when I remove the text from the input field to set it to nothing,  or make a change in the input field, for example if I type the date manually, nothing happens, when I save, it doesn't take the value I entered.  The date in my update function stays as before. 

It doesn't let me set the date to nothing. 
My update function looks like this

```
        ToDatePicker datePickerMsg ->
            let
                (( newDatePicker,  mDate )) =
                    DatePicker.update defaultSettings datePickerMsg model.datePicker


                date =
                    case mDate of
                        DatePicker.Picked changedDate ->
                            Just changedDate
                        _ ->
                            model.date

                newOrg =
                    updateOrganization model.organization (ChgContractDate (formatMaybeDate date))
            in
            ( { model | date = date, datePicker = newDatePicker, organization = newOrg }, Cmd.none )
```

Where formatMaybeDate date is 
```formatMaybeDate : Maybe Date -> String
formatMaybeDate d =
    case d of
        Nothing ->
            ""

        Just date ->
            Date.toIsoString date
```

The branch  Nothing never gets hit, even after I remove everything in the datepicker input field. 
Any advice on how to do that?

**Comment by JDemler** [comment]
Very welcome :)

Your followup is possibly related to #20 and #19.
Please check these issues and open a new issue if they do not answer your questions.
