### ISSUE TITLE
Remove date from text field should get us back to starting state (datepicker not filled in)

### ISSUE THREAD

**Issue by paulsonkoly** [CurrySoftware/elm-datepicker#26]
As far as I understand the current interface there is no way for a user to remove a date selection. When we start the date might not be picked (Nothing) which seems to be a supported concept as the example shows

```elm
  case dateEvent of
                        Picked newDate ->
                            Just newDate
```
 and https://ellie-app.com/3WbsRpXXzJ5a1 does it, but once a date is once picked there is no way to get back to this state. The Picked dateEvent is a Date not a Maybe Date, and if the user clears the text field and leaves empty text the Picked is not fired. FailedInput is fired as the empty text is not parsed as a date, but then one cannot distinguish between non-filled in valid forms versus filled in invalid ones.

It's debatable if this is a bug, feels more like a design issue, but one would expect the starting state to be reachable again with user interaction.

**Comment by JDemler** [comment]
You have multiple options here: 

1. Create your own reset button. This is possible and straightforward, because the datepicker itself does not have state.
2. Treat invalid input as resetting the datepicker. I don't quite understand your problem with this approach.

> FailedInput is fired as the empty text is not parsed as a date, but then one cannot distinguish between non-filled in valid forms versus filled in invalid ones.

Maybe you can elaborate?

Cheers

**Comment by paulsonkoly** [comment]
Thank you for your feedback. 

1. A reset button doesn't feel intuitive to me, when the user first sees the datepicker it's empty, with Nothing in the state. If they write some valid date in it, then the state will have Just the date. Now if they change their mind and want to not fill in that state, I believe the natural user interaction that undoes what has been done is to delete the text that was typed in.

2. Treat invalid input as resetting the datepicker. The problem is that I need to be able to tell a filled in invalid input -> (show user form errors, disable submit), from a form that does not have the date filled in. If all I ever get back is `FailedInput (Invalid "Expected a date in ISO 8601 format")` for both cases I can't tell them apart.

I think I could work around this by peeking into the internal messages of datepicker, and tracking the text myself as well, but it's obviously not an optimal solution. For the moment I just hacked in returning Picked (Maybe Date) which is super easy, but I understand it would be an interface breaking change.

**Comment by JDemler** [comment]
Hm... I think I understand your problem.

Just as a pointer: You can set the date parser yourself. There you could check for empty strings. But this would be hacky, too.

I think a third `InputError` variant `EmptyString` would be an acceptable fit. Then the developer could act whatever entering an empty string into the datepicker would mean for them.

**Comment by paulsonkoly** [comment]
> I think a third InputError variant EmptyString would be an acceptable fit. 

That would definitely work.

Cheers
