### ISSUE TITLE
`cellFormatter` API should be more flexible

### ISSUE THREAD

**Issue by kornicameister** [CurrySoftware/elm-datepicker#3]
So this is more like observation. Anyway, I've been playing around with styling of the `elm-datapicker` to suits my needs and it's been quite tricky. I've been wondering if it'd not be easier to maybe make `cellFormatter` function similar to

```cellFormatter: {day: String, isDisabled: Bool, isSelected: Bool, isToday: Bool}```. That way we could pretty much get rid of certain styles and classes shipped with the library and replace it with styling the content of the cell more based in Elm with an aid of caller `Model`.

For example, given bulma I'm using, 

```
cellFormatter = 
  \{day, isDisabled, isSelected, isToday} ->
     Html.Button
       [ Attributes.classList [
         ("button is-fullwidth is-small", True)
         , ("is-white", not <| isSelected)
         , ("is-primary is-active", isSelected)
         , ("has-text-weight-bold", isToday)]
        , Attributes.disabled isDisabled
       ]
       [ Html.text day ]
```

That somehow seems nicer and easier to control from withing the module that uses the picker.

That's the idea, I don't how much much we could take this further (regarding other styles) if you see a value here.

**Comment by JDemler** [comment]
If I understand you correctly, you want to specify the CSS classes that are emitted yourself.
It is already possible to specify a custom namespace by using the `classNamespace` setting.

I find the proposed API change unnecessarily complex for something that could also be handled by CSS or a CSS preprocessor.

**Comment by kornicameister** [comment]
Yes, the point is that with CSS it seemed a little bit more disconnected from the framework I am using. But after digging more it seems like it's just bulma that isn't entirely happy about writing:

```
.#{$datepicker-ns}day button { 
  @extend .button
}
```

Ok fair enough, I think that we can close that down. 

BTW. Don't get this the wrong way. My intention was to point out that it might sometime tricky to apply the styling in the desired way with the current implementation. For one, bulma is still (obviously) incapable of providing that. It's not a fault of this library of course. It's just that with the proposed function I'd generate a specific HTML chunk that's in sync with my model and all that is based inside of Elm module.
