### ISSUE TITLE
Update dependency on justinmimbs/date

### ISSUE THREAD

**Issue by stephenreddek** [CurrySoftware/elm-datepicker#8]
First off, thank you for taking on the maintenance of this package! It really is an important package for the ecosystem.

Can you upgrade the dependency on `justinmimbs/date` to support version 3 as well? Should be able to allow both 2 and 3. Thank you!

**Comment by JDemler** [comment]
Done. Thanks for noticing!

Published with version [2.1.1](https://package.elm-lang.org/packages/CurrySoftware/elm-datepicker/2.1.1/)
